# TODO:
# 1. add network and how now it is work?
# 2. add volume for persistent data on db
# 3. add resource management for cpu & memory
# 4. add health check for all container
# 5. reverse proxy (I think now is not meaning in my project)
version: '3.8'

services:
  app:
    build: .
    container_name: nest-auth
    ports:
      - "3001:3001"   # Adjust this to your app's internal port
    environment:
      - PORT=3000
      - DATABSE_HOST=db
      - DATABSE_PORT=5432
      - DATABSE_USERNAME=postgres
      - DATABSE_PASSWOED=123456
      - DATABSE_NAME=auth
      - JWT_SECRET=9d23b0970e84873209b83c405206c186c9053640e9a961d0dcad822db93434e3
      - JWT_EXPIRES_IN=360s
      - NODE_ENV=prod
      - PASSWORD_PEPPER=Dpo3Mlr&S5MTvdW7ZZP$K6vC&AnX%nv*Z9n-Pq+0c8)bwO(YCCGA
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: auth



