openapi: 3.0.0
paths:
  /auth/signUp:
    post:
      operationId: AuthController_signUp
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpDto'
      responses:
        '201':
          description: 'profile of user added'
      tags:
        - Auth
  /auth/logIn:
    post:
      operationId: AuthController_logIn
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogInDto'
      responses:
        '201':
          description: 'in response just says ok, and set JWT token on http cookies'
      tags:
        - Auth
  /auth/profile:
    get:
      operationId: AuthController_getProfile
      parameters: []
      responses:
        '200':
          description: 'get profile that was logged in'
      tags:
        - Auth
    patch:
      operationId: AuthController_changeProfile
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileDto'
      responses:
        '200':
          description: 'updated profile info'
      tags:
        - Auth
  /auth/active:
    patch:
      operationId: AuthController_activeUser
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActiveUserDto'
      responses:
        '200':
          description: 'profile activation status'
      tags:
        - Auth
  /auth/users:
    get:
      operationId: AuthController_getAllUsers
      parameters: []
      responses:
        '200':
          description: 'api for get all usernames in db'
      tags:
        - Auth
  /auth/image/{username}:
    get:
      operationId: AuthController_getProfileImage
      parameters:
        - name: username
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: 'profile image as raw file'
      tags:
        - Auth
  /auth/image:
    post:
      operationId: AuthController_updateProfileImage
      parameters: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ProfileImageDto'
      responses:
        '201':
          description: 'success message'
        '400': 
          description: 'file limit or file type has some error'
      tags:
        - Auth
  
  /task/item:
    get:
      operationId: AuthController_getItemsList
      parameters:
        - name: sortFeild
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Task
    post:
      operationId: TaskController_addItem
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddItemDto'
      responses:
        '201':
          description: ''
      tags:
        - Task
    patch:
      operationId: TaskController_updateItem
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateItemDto'
      responses:
        '200':
          description: ''
      tags:
        - Task
    delete:
      operationId: TaskController_deleteItem
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteItemDto'
      responses:
        '200':
          description: ''
      tags:
        - Task
  /task/item/{itemId}:
    get:
      operationId: AuthController_getItemDetail
      parameters:
        - name: itemId
          required: true
          in: path
          schema:
            type: string
        - name: sortFeild
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Task
  /task/item/reports/{itemId}:
    post:
      operationId: AuthController_getItemDetail
      parameters:
        - name: itemId
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Task
    put:
      operationId: AuthController_getItemDetail
      parameters:
        - name: itemId
          required: true
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Task
  /task/item/note/{itemId}:
    put:
      operationId: AuthController_getItemDetail
      parameters:
        - name: itemId
          required: true
          in: path
          schema:
            type: string
        - name: sortFeild
          in: path
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Task
  /task/subitem:
    post:
      operationId: AuthController_getItemDetail
      responses:
        '200':
          description: ''
      tags:
        - Task


info:
  title: Project Management API
  description: API for managing projects
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
  schemas:
    SignUpDto:
      type: object
      properties:
        username:
          type: string
          example: mohammad
          description: the unique username
        password:
          type: string
          example: 1qaz!QAZ
          description: strong password
        repeatPassword:
          type: string
          example: 1qaz!QAZ
          description: repeat the password
        email:
          type: string
          example: mohamamd@gmail.com
          description: a valid gmail
      required:
        - username
        - password
        - repeatPassword
        - email
    LogInDto:
      type: object
      properties:
        username:
          type: string
          example: mohammad
          description: username or email
        password:
          type: string
          example: 1qaz!QAZ
          description: password for user
      required:
        - username
        - password
    ActiveUserDto:
      type: object
      properties:
        username:
          type: string
          example: mohammad
          description: username that need change activation
        setActive:
          type: boolean
          example: true
          description: boolean that show is user set to active or not active
      required:
        - userId
        - setActive
    ProfileDto:
      type: object
      properties:
        username:
          type: string
          example: mohammad
          description: username
        firstName:
          type: string
          example: mohammad
          description: first name
        lastName:
          type: string
          example: afzal
          description: last name
        email:
          type: string
          example: mohammad@gmail.com
          description: email
        job:
          type: string
          example: data engineer
          description: job
        bio:
          type: string
          example: bio...
          description: bio
        birthday:
          format: date-time
          type: string
          example: '2001-10-13'
          description: birthday
    ProfileImageDto:
      type: object
      properties:
        profileImage:
          type: string
          description: image for this profile
          format: binary
      required:
        - profileImage
